apiVersion: v1
kind: ConfigMap
metadata:
name: web-content
labels:
app: web
data:
index.html: |
<html><body style="font-family:sans-serif">
<h1>Hello from DevOps → Kubernetes!</h1>
<p>Student: ANIL </p>
<p>Scaled and served via K3s (k3d) inside GitHub Codespaces.</p>
</body></html>
